### PR TITLE
Several simple fixes

### PR DESCRIPTION
**Pull request by NyaMisty**
1. Add support to import function so that the vtable scan won't stop due to the decompilation failure
2. Automatically scan the whole vtable to get better struct.

### CODE REVIEW

**Comment by NyaMisty** [comment]
Please ignore the "Extend the containing structure functionality" commit, it's my dirty hacking, I've reverted it in the last commit.

**Comment by igogo-x86** [comment]
Hello!

About automatic calling `scan_virtual_functions` in VirtualTable constructor - I deliberately left it for the researcher to decide whether to scan all functions or not. The reason is because some functions (due to optimization) can be without `this` first argument and in result scanner may scan variable which is not actually pointer to reconstructed structure.

Could you please drop the case where virtual tables have imported methods? And I see couple of problems in your solution - 1) `imported_ea` list is not cleared after loading new binary. 2) If we rebase program (for example after debugging) that list will become incorrect. So we need to keep offsets from the program beginning (`idaapi.get_imagebase()`) and add current offset when compare in `is_imported_ea(ea)` function.

**Comment by NyaMisty** [comment]
I have to apologize for my late reply :(
My solutions are just little hacks, so I didn't thought about those (maybe corner) cases. I'm really sorry, and I'll improve my code quality later.
As for those virtual tables, I bumped into some drivers in MacOS, and here's the sample:
[](https://drive.google.com/open?id=0B_OHM3FuQeQzTF9pb1ZLbTdwTms)
which is the NVMe driver extracted from MacOS Sierra
You can see the virtual table at 0x20DF0.

**Comment by igogo-x86** [comment]
Looks like you forgot to append sample file

**Comment by NyaMisty** [comment]
Ouch I'm so caseless....
https://drive.google.com/open?id=0B_OHM3FuQeQzTF9pb1ZLbTdwTms
here it is.

**Pull request merged**
